/**
 * Theme manifest — generated by scripts/gen-theme-manifest.ts.
 * One tiny entry per built-in theme: name + a few preview colors for the picker.
 * Picker renders from this without loading any theme body (see ./load.ts).
 */

export type ThemePreview = {
  primary: string | null
  accent: string | null
  background: string | null
}

export const PREVIEW: Record<string, ThemePreview> = {
  "ares": { primary: "#C7A96B", accent: "#DD4A3A", background: "#2A1212" },
  "aura": { primary: "#a277ff", accent: "#a277ff", background: "#0f0f0f" },
  "ayu": { primary: "#59C2FF", accent: "#E6B450", background: "#0B0E14" },
  "carbonfox": { primary: "#33b1ff", accent: "#ff7eb6", background: "#161616" },
  "catppuccin-frappe": { primary: "#8da4e2", accent: "#f4b8e4", background: "#303446" },
  "catppuccin-macchiato": { primary: "#8aadf4", accent: "#f5bde6", background: "#24273a" },
  "catppuccin": { primary: "#89b4fa", accent: "#f5c2e7", background: "#1e1e2e" },
  "charizard": { primary: "#FFD39A", accent: "#F29C38", background: "#2B160E" },
  "cobalt2": { primary: "#0088ff", accent: "#2affdf", background: "#193549" },
  "cursor": { primary: "#88c0d0", accent: "#88c0d0", background: "#181818" },
  "daylight": { primary: "#233662", accent: "#597FE9", background: "#101014" },
  "default": { primary: "#FFD700", accent: "#FFBF00", background: "#1a1a2e" },
  "dracula": { primary: "#bd93f9", accent: "#8be9fd", background: "#282a36" },
  "everforest": { primary: "#a7c080", accent: "#d699b6", background: "#2d353b" },
  "flexoki": { primary: "#DA702C", accent: "#8B7EC8", background: "#100F0F" },
  "github": { primary: "#58a6ff", accent: "#39c5cf", background: "#0d1117" },
  "gruvbox": { primary: "#83a598", accent: "#8ec07c", background: "#282828" },
  "kanagawa": { primary: "#7E9CD8", accent: "#D27E99", background: "#1F1F28" },
  "lucent-orng": { primary: "#EC5B2B", accent: "#FFF7F1", background: "transparent" },
  "material": { primary: "#82aaff", accent: "#89ddff", background: "#263238" },
  "matrix": { primary: "#2eff6a", accent: "#c770ff", background: "#0a0e0a" },
  "mercury": { primary: "#8da4f5", accent: "#8da4f5", background: "#171721" },
  "mono": { primary: "#e6edf3", accent: "#aaaaaa", background: "#1F1F1F" },
  "monokai": { primary: "#66d9ef", accent: "#a6e22e", background: "#272822" },
  "nightowl": { primary: "#82AAFF", accent: "#c792ea", background: "#011627" },
  "nord": { primary: "#88C0D0", accent: "#8FBCBB", background: "#2E3440" },
  "one-dark": { primary: "#61afef", accent: "#56b6c2", background: "#282c34" },
  "opencode": { primary: "#fab283", accent: "#9d7cd8", background: "#0a0a0a" },
  "orng": { primary: "#EC5B2B", accent: "#FFF7F1", background: "#0a0a0a" },
  "osaka-jade": { primary: "#2DD5B7", accent: "#549e6a", background: "#111c18" },
  "palenight": { primary: "#82aaff", accent: "#89ddff", background: "#292d3e" },
  "poseidon": { primary: "#A9DFFF", accent: "#5DB8F5", background: "#0F2440" },
  "rosepine": { primary: "#9ccfd8", accent: "#ebbcba", background: "#191724" },
  "sisyphus": { primary: "#F5F5F5", accent: "#E7E7E7", background: "#202020" },
  "slate": { primary: "#7eb8f6", accent: "#8EA8FF", background: "#151C2F" },
  "solarized": { primary: "#268bd2", accent: "#2aa198", background: "#002b36" },
  "synthwave84": { primary: "#36f9f6", accent: "#b084eb", background: "#262335" },
  "tokyonight": { primary: "#82aaff", accent: "#ff966c", background: "#1a1b26" },
  "vercel": { primary: "#0070F3", accent: "#8E4EC6", background: "#000000" },
  "vesper": { primary: "#FFC799", accent: "#FFC799", background: "#101010" },
  "warm-lightmode": { primary: "#9D681D", accent: "#CE661C", background: "#101014" },
  "zenburn": { primary: "#8cd0d3", accent: "#93e0e3", background: "#3f3f3f" },
}

export const NAMES: readonly string[] = Object.keys(PREVIEW).sort()
